# Name can be anything you want
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually with a trigger
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ozgeeodabass/workflows/blog-post-workflow@master
        with:
          # you can change this to your own RSS feed
          feed_list: "https://medium.com/@ozgeeodabassg"
          max_post_count: "3"
